#!/usr/bin/env bash
# This script cconfigures an Ubuntu server with specific settings.

if grep -E "127\.0\.0\.1[[:space:]]+localhost" /etc/hosts; then
    sudo sed -i '/localhost/c\127.0.0.2 localhost' /etc/hosts
else
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
fi

if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else 
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi
cat /etc/hosts
